[package]
name = "viper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
elasticsearch = "8.5.0-alpha.1"
log = "0.4.17"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
stderrlog = "0.5.4"
url = "2.3.1"
